# Generated by Django 4.1.2 on 2022-10-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminshoppost',
            old_name='id',
            new_name='shop_id',
        ),
    ]
