# Generated by Django 4.1.2 on 2022-10-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_id_adminshoppost_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminshoppost',
            name='shop_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
