# Generated by Django 4.1.2 on 2022-10-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_shop_id_adminshoppost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminshoppost',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
