# Generated by Django 4.1.2 on 2022-10-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_adminshoppost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminshoppost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
