# Generated by Django 4.1.2 on 2022-10-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_adminshoppost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminshoppost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
