# Generated by Django 4.0.5 on 2022-10-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
